/* 
 * Copyright 2014 Lukas Stratmann
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package util;

import java.util.Calendar;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * Handles string internationalization. Automatically generated by Eclipse.
 * @author lumpiluk
 */
public class Messages {
	
	public static enum ErrorType {
		UI("Ui"), DB("DB"), UNKNOWN("Unknown");
		
		private String s;
		
		private ErrorType(String s) {
			this.s = s;
		}
		
		public String toString() {
			return s;
		}
	}
	
	private static final String BUNDLE_NAME = "messages"; //$NON-NLS-1$

	private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle
			.getBundle(BUNDLE_NAME, new Locale("de", "DE"));

	private Messages() {
	
	}
	
	public static ResourceBundle getBundle() {
		return RESOURCE_BUNDLE;
	}
	
	public static String getShortDayOfWeek(int dayOfWeek) 
			throws IllegalArgumentException {
		switch (dayOfWeek) {
		case Calendar.MONDAY:
			return getString("Calendar.Weekdays.Monday.Short");
		case Calendar.TUESDAY:
			return getString("Calendar.Weekdays.Tuesday.Short");
		case Calendar.WEDNESDAY:
			return getString("Calendar.Weekdays.Wednesday.Short");
		case Calendar.THURSDAY:
			return getString("Calendar.Weekdays.Thursday.Short");
		case Calendar.FRIDAY:
			return getString("Calendar.Weekdays.Friday.Short");
		case Calendar.SATURDAY:
			return getString("Calendar.Weekdays.Saturday.Short");
		case Calendar.SUNDAY:
			return getString("Calendar.Weekdays.Sunday.Short");
		default:
			throw new IllegalArgumentException();			
		}
	}
	
	public static String getMonth(int month) throws IllegalArgumentException {
		switch (month) {
		case Calendar.JANUARY: return getString("Calendar.Months.January");
		case Calendar.FEBRUARY: return getString("Calendar.Months.February");
		case Calendar.MARCH: return getString("Calendar.Months.March");
		case Calendar.APRIL: return getString("Calendar.Months.April");
		case Calendar.MAY: return getString("Calendar.Months.May");
		case Calendar.JUNE: return getString("Calendar.Months.June");
		case Calendar.JULY: return getString("Calendar.Months.July");
		case Calendar.AUGUST: return getString("Calendar.Months.August");
		case Calendar.SEPTEMBER: return getString("Calendar.Months.September");
		case Calendar.OCTOBER: return getString("Calendar.Months.October");
		case Calendar.NOVEMBER: return getString("Calendar.Months.November");
		case Calendar.DECEMBER: return getString("Calendar.Months.December");
		default: throw new IllegalArgumentException();
		}
	}
	
	public static void showError(Exception e, ErrorType t) {
		e.printStackTrace();
		showError(Messages.getString(String.format("Error.%s.text", t))
					+ "\n" + e.toString(), t);
	}
	
	public static void showError(String s, ErrorType t) {
		/*Dialogs.create()
			.title(Messages.getString(String.format("Error.%s.title", t)))
			.message(s)
			.style(DialogStyle.NATIVE)
			.showError();*/ // TODO find alternative. Dialogs is deprecated and has been moved to OpenJFX
		System.out.println(Messages.getString(String.format("Error.%s.title", t)) + " | " + s);
	}

	public static String getString(String key) {
		try {
			return RESOURCE_BUNDLE.getString(key);
		} catch (MissingResourceException e) {
			return '!' + key + '!';
		}
	}
}
