package application;

import java.util.Calendar;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * Handles string internationalization. Automatically generated by Eclipse.
 * @author lumpiluk
 */
public class Messages {
	private static final String BUNDLE_NAME = "messages"; //$NON-NLS-1$

	private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle
			.getBundle(BUNDLE_NAME, new Locale("de", "DE"));

	private Messages() {
	}
	
	public static ResourceBundle getBundle() {
		return RESOURCE_BUNDLE;
	}
	
	public static String getShortDayOfWeek(int dayOfWeek) 
			throws IllegalArgumentException {
		switch (dayOfWeek) {
		case Calendar.MONDAY:
			return getString("Weekdays.Monday.Short");
		case Calendar.TUESDAY:
			return getString("Weekdays.Tuesday.Short");
		case Calendar.WEDNESDAY:
			return getString("Weekdays.Wednesday.Short");
		case Calendar.THURSDAY:
			return getString("Weekdays.Thursday.Short");
		case Calendar.FRIDAY:
			return getString("Weekdays.Friday.Short");
		case Calendar.SATURDAY:
			return getString("Weekdays.Saturday.Short");
		case Calendar.SUNDAY:
			return getString("Weekdays.Sunday.Short");
		default:
			throw new IllegalArgumentException();			
		}
	}

	public static String getString(String key) {
		try {
			return RESOURCE_BUNDLE.getString(key);
		} catch (MissingResourceException e) {
			return '!' + key + '!';
		}
	}
}
